const state = { trained: JSON.parse(localStorage.getItem('fitia-trained') || '[]'), month: 8, year: 2026 };
const monthNames = ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
const routes = { inicio:'Visão geral', treinos:'Meus treinos', calendario:'Calendário', configuracoes:'Configurações' };
const pad = n => String(n).padStart(2,'0');
function key(y,m,d){ return `${y}-${pad(m+1)}-${pad(d)}`; }
function go(route){ document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view')); document.querySelector(`#view-${route}`)?.classList.add('active-view'); document.querySelectorAll('.nav-link[data-route]').forEach(l=>l.classList.toggle('active', l.dataset.route===route)); document.getElementById('pageName').textContent=routes[route] || 'Visão geral'; document.querySelector('.sidebar').classList.remove('open'); }
function calendar(target, full=false){ const el=document.getElementById(target); if(!el)return; el.innerHTML=''; const first=new Date(state.year,state.month,1); let start=(first.getDay()+6)%7; const days=new Date(state.year,state.month+1,0).getDate(); const prevDays=new Date(state.year,state.month,0).getDate(); for(let i=0;i<start;i++){const s=document.createElement('span');s.className='empty';s.textContent=prevDays-start+i+1; s.style.opacity='.25'; el.append(s)} for(let d=1;d<=days;d++){const s=document.createElement('span');s.textContent=d; const k=key(state.year,state.month,d); if(state.trained.includes(k))s.classList.add('done'); if(k==='2026-09-28')s.classList.add('today'); if(full){s.onclick=()=>{state.trained=state.trained.includes(k)?state.trained.filter(x=>x!==k):[...state.trained,k];localStorage.setItem('fitia-trained',JSON.stringify(state.trained));calendar('fullCalendar',true);calendar('miniCalendar');updateSummary();toast(state.trained.includes(k)?'Treino marcado! Sua constância agradece. ✦':'Treino desmarcado.')} } el.append(s)} }
function updateSummary(){const count=state.trained.filter(x=>x.startsWith(`${state.year}-${pad(state.month+1)}`)).length; const c=document.getElementById('monthCount'); if(c)c.textContent=count; const p=document.getElementById('monthProgress');if(p)p.style.width=`${Math.min(100,count/24*100)}%`; const t=document.getElementById('calendarTitle');if(t)t.textContent=`${monthNames[state.month]} ${state.year}`}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
document.querySelectorAll('[data-route]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();go(a.dataset.route)})); document.querySelectorAll('[data-scroll="treinos"]').forEach(b=>b.addEventListener('click',()=>go('treinos'))); document.querySelectorAll('.month-arrow').forEach((b,i)=>{if(b.id==='prevMonth')b.onclick=()=>{state.month--;if(state.month<0){state.month=11;state.year--}calendar('fullCalendar',true);updateSummary()};if(b.id==='nextMonth')b.onclick=()=>{state.month++;if(state.month>11){state.month=0;state.year++}calendar('fullCalendar',true);updateSummary()}}); document.getElementById('mobileMenu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
const modal=document.getElementById('loginModal'); document.getElementById('loginButton').onclick=()=>modal.classList.add('open'); document.getElementById('profileButton').onclick=()=>modal.classList.add('open');document.getElementById('closeModal').onclick=()=>modal.classList.remove('open');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')};document.getElementById('loginForm').onsubmit=e=>{e.preventDefault();modal.classList.remove('open');document.getElementById('loginButton').innerHTML='<span>✓</span> João';toast('Login realizado com sucesso!')}; document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active')});document.querySelectorAll('.toggle').forEach(b=>b.onclick=()=>b.classList.toggle('on'));
calendar('miniCalendar');calendar('fullCalendar',true);updateSummary();

async function loadAccount(){try{const response=await fetch('/api/auth/me');const data=await response.json();if(data.user){modal.classList.remove('open');document.getElementById('loginButton').innerHTML=`<span>✓</span> ${data.user.name.split(' ')[0]}`;const checkins=await fetch('/api/checkins');if(checkins.ok){state.trained=await checkins.json();calendar('miniCalendar');calendar('fullCalendar',true);updateSummary()}}}catch(error){console.info('API indisponível: usando modo local.')}}
document.getElementById('loginForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;const button=form.querySelector('button[type="submit"]');const email=form.querySelector('input[type="email"]').value;const password=form.querySelector('input[type="password"]').value;button.disabled=true;button.innerHTML='Entrando...';try{const response=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Não foi possível entrar.');modal.classList.remove('open');document.getElementById('loginButton').innerHTML=`<span>✓</span> ${data.user.name.split(' ')[0]}`;toast(`Bem-vindo, ${data.user.name.split(' ')[0]}!`);const checkins=await fetch('/api/checkins');if(checkins.ok){state.trained=await checkins.json();calendar('miniCalendar');calendar('fullCalendar',true);updateSummary()}}catch(error){toast(error.message+' Use joao@fitia.com / 123456.')}finally{button.disabled=false;button.innerHTML='Entrar <span>→</span>'}};
document.getElementById('fullCalendar').addEventListener('click',event=>{const day=Number(event.target.textContent);if(!day)return;const date=key(state.year,state.month,day);fetch('/api/checkins',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({date,trained:state.trained.includes(date)})}).catch(()=>{});});
loadAccount();

const loginFormElement=document.getElementById('loginForm');const emailField=document.getElementById('loginEmail');const passwordField=document.getElementById('loginPassword');const emailError=document.getElementById('emailError');const passwordError=document.getElementById('passwordError');const loginStatus=document.getElementById('loginStatus');
function validateEmail(value){return /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/i.test(value.trim())}
function validateLogin(){let valid=true;emailError.textContent='';passwordError.textContent='';loginStatus.textContent='';document.querySelectorAll('.form-field').forEach(field=>field.classList.remove('has-error'));if(!emailField.value.trim()){emailError.textContent='Informe seu e-mail.';emailField.closest('.form-field').classList.add('has-error');valid=false}else if(!validateEmail(emailField.value)){emailError.textContent='Digite um e-mail válido.';emailField.closest('.form-field').classList.add('has-error');valid=false}if(!passwordField.value.trim()){passwordError.textContent='Informe sua senha.';passwordField.closest('.form-field').classList.add('has-error');valid=false}else if(passwordField.value.length<6){passwordError.textContent='A senha deve ter pelo menos 6 caracteres.';passwordField.closest('.form-field').classList.add('has-error');valid=false}if(!valid)loginStatus.textContent='Revise os campos destacados para continuar.';return valid}
loginFormElement.addEventListener('submit',event=>{if(!validateLogin()){event.preventDefault();event.stopImmediatePropagation()}},true);[emailField,passwordField].forEach(field=>field.addEventListener('input',()=>{if(field===emailField&&emailField.value)emailError.textContent='';if(field===passwordField&&passwordField.value)passwordError.textContent='';field.closest('.form-field').classList.remove('has-error');loginStatus.textContent=''}));document.getElementById('togglePassword').addEventListener('click',()=>{const visible=passwordField.type==='text';passwordField.type=visible?'password':'text';document.getElementById('togglePassword').setAttribute('aria-label',visible?'Exibir senha':'Ocultar senha');document.getElementById('togglePassword').setAttribute('aria-pressed',String(!visible));document.getElementById('passwordEye').textContent=visible?'◉':'◌'});document.getElementById('forgotPassword').addEventListener('click',event=>{event.preventDefault();toast('Em breve você poderá recuperar sua senha por e-mail.')});
